
source = ~/.config/hypr/colors.conf

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MODULAR CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/settings.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/keybindings.conf

input {
    touchpad {
        tap-to-click = true
        clickfinger_behavior = true
     }
}

# HyprMod managed settings
source = ~/.config/hypr/hyprland-gui.conf
