preload = /home/olek/Pictures/Wallpapers/197424-nature-lake-sunset-landscape-ultrahd-4k-wallpaper.jpg
wallpaper = ,/home/olek/Pictures/Wallpapers/197424-nature-lake-sunset-landscape-ultrahd-4k-wallpaper.jpg
splash = false
ipc = on
