# Basic colors
foreground              #e0e4db
background              #101510
selection_foreground    #d4e8d0
selection_background    #3a4b3a

# Cursor colors
cursor                  #9dd49e
cursor_text_color       #023913

# URL underline color when hovering with mouse
url_color               #a1ced6

# Kitty window border colors
active_border_color     #9dd49e
inactive_border_color   #424940
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #b8f0b8
active_tab_background   #1e5027
inactive_tab_foreground #c1c9be
inactive_tab_background #1c211c
tab_bar_background      #101510

# Colors for marks
mark1_foreground #023913
mark1_background #9dd49e
mark2_foreground #243424
mark2_background #b8ccb5
mark3_foreground #00363d
mark3_background #a1ced6

# The 16 terminal colors
# black
color0 #424940
color8 #8c9389

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #9dd49e
color10 #b8f0b8

# yellow
color3  #a1ced6
color11 #bdeaf2

# blue
color4  #b8ccb5
color12 #d4e8d0

# magenta
color5  #1e5027
color13 #37693d

# cyan
color6  #3a4b3a
color14 #1f4d54

# white
color7  #c1c9be
color15 #e0e4db
