[Appearance]
color_scheme_path=/home/olek/.config/qt5ct/colors/matugen.conf
custom_palette=true
standard_dialogs=default
style=Fusion
stylesheets=/home/olek/.config/qt5ct/qss/matugen-style.qss

[Interface]
stylesheets=/home/olek/.config/qt5ct/qss/matugen-style.qss

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\xb3\0\0\x2\xb2\0\0\0\0\0\0\0\0\0\0\x3\xbb\0\0\x2\xb2\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xb3\0\0\x2\xb2)
