exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon
exec-once = eww daemon
exec-once = swaync
exec-once = hypridle
exec-once = waybar
exec-once = ~/.config/hypr/scripts/init.sh
exec-once = playerctld
exec-once = swayosd-server --top-margin 0.9 --style "$HOME/.config/swayosd/style.css"
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/volume_listener.sh
exec-once = mullvad-vpn
exec-once = systemctl --user start xdg-desktop-portal-hyprland
