#  ◈ WINDOW & LAYER RULES

windowrule {
    name = "yad_popup"
    match:class = ^(yad)$
    float = on
    move = 1628 62
    pin = on
}


layerrule {
    name = "lr_wlogout"
    match:namespace = ^(wlogout)$
    blur = on
}

layerrule {
    name = "lr_eww"
    match:namespace = ^(eww-.*)$
    blur = on
}

layerrule {
    name = "lr1"
    match:namespace = ^(volume_osd)$
    no_anim = on
}

layerrule {
    name = "lr2"
    match:namespace = ^(brightness_osd)$
    no_anim = on
}

layerrule {
    name = "lr3"
    match:namespace = hyprpicker
    no_anim = on
}

layerrule {
    name = "lr4"
    match:namespace = ext-session-lock
    blur = on
    ignore_alpha = 0.2
}
